name: Ginny

options:
  deploymentTarget:
    iOS: "26.0"
  createIntermediateGroups: true
  developmentLanguage: en

packages:
  AtprotoOAuth:
    url: https://github.com/germ-network/AtprotoOAuth.git
    from: 0.5.11
  AtprotoClient:
    url: https://github.com/germ-network/AtprotoClient.git
    from: 0.6.0
  AtprotoTypes:
    url: https://github.com/germ-network/AtprotoTypes.git
    from: 0.4.6
  GermConvenience:
    url: https://github.com/germ-network/GermConvenience.git
    from: 0.2.4
  OAuth4Swift:
    url: https://github.com/germ-network/oauth4swift.git
    from: 0.5.0
  SwiftAtproto:
    url: https://github.com/nnabeyang/swift-atproto.git
    from: 0.42.2
  SwiftStreamingMarkdown:
    url: https://github.com/espeon/SwiftStreamingMarkdown.git
    branch: feature/fast-fade

settings:
  base:
    SWIFT_VERSION: "6.0"
    CLANG_ENABLE_MODULES: YES
    SWIFT_STRICT_CONCURRENCY: complete

targets:
  Ginny:
    type: application
    platform: iOS
    info:
      path: Ginny/Info.plist
      properties:
        UILaunchScreen: {}
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
        NSSupportsLiveActivities: true
        CFBundleURLTypes:
          - CFBundleTypeRole: Editor
            CFBundleURLSchemes:
              - computer.mew.rina
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        "UISupportedInterfaceOrientations~ipad":
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    sources:
      - path: Ginny
      - path: theme_manifest.json
        buildPhase: resources
    dependencies:
      - package: AtprotoOAuth
        product: AtprotoOAuth
      - package: AtprotoClient
        product: AtprotoClient
      - package: AtprotoTypes
        product: AtprotoTypes
      - package: GermConvenience
        product: GermConvenience
      - package: OAuth4Swift
        product: OAuth4Swift
      - package: SwiftAtproto
        product: SwiftAtproto
      - package: SwiftStreamingMarkdown
        product: SwiftStreamingMarkdown
    settings:
      base:
        DEVELOPMENT_TEAM: P2B3GABB6H
        PRODUCT_BUNDLE_IDENTIFIER: fm.teal.ginny
        TARGETED_DEVICE_FAMILY: "1,2"
    scheme:
      testTargets:
        - GinnyTests
      gatherCoverageData: true

  GinnyTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: GinnyTests
    dependencies:
      - target: Ginny
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.ginny.tests
